services:
  mongo-user:
    image: mongo:8
    container_name: mongo_user_db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_user_data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - PERSISTENCE=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-bootstrap:/etc/localstack/init/ready.d/
    healthcheck:
      test: >-
        curl -sf localhost:4566/_localstack/init/ready | grep -q '"completed": true,'
      interval: 1m
      timeout: 5s
      start_period: 1m
      retries: 5

  user-service:
    build: ./services/user-service
    container_name: user_service
    restart: always
    depends_on:
      localstack:
        condition: service_healthy
      mongo-user:
        condition: service_started
    environment:
      MONGO_URI: mongodb://admin:password@mongo_user_db:27017/userdb?authSource=admin
      AWS_REGION: us-east-1
      PORT: 4000
    ports:
      - "4001:4000"

  auth-service:
    build: ./services/auth-service
    container_name: auth_service
    restart: always
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://admin:password@mongo_user_db:27017/userdb?authSource=admin
      AWS_USER_SQS: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/user-queue
      AWS_REGION: us-east-1
      PORT: 4000
    ports:
      - "4002:4000"  

volumes:
  mongo_user_data:
  localstack_data:
