version: '3.8'

services:
  mongo-user:
    image: mongo:8
    container_name: mongo_user_db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_user_data:/data/db

  # mongo-order:
  #   image: mongo:8
  #   container_name: mongo_order_db
  #   restart: always
  #   ports:
  #     - "27019:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongo_order_data:/data/db

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack

  user-service:
    build: ./services/user-service
    container_name: user_service
    restart: always
    depends_on:
      - mongo-user
      - localstack
    environment:
      MONGO_URI: mongodb://admin:password@mongo_user_db:27017/userdb?authSource=admin
      AWS_SQS_URL: http://localstack:4566/000000000000/user-queue
      AWS_REGION: us-east-1
    ports:
      - "4001:4000"

volumes:
  mongo_user_data:
  # mongo_order_data:
  localstack_data:
