FROM node:23-alpine

RUN npm install -g ts-node nodemon typescript

WORKDIR /app

COPY ./services /app

WORKDIR /app/shared
COPY ./services/shared/package*.json ./
RUN npm install

WORKDIR /app/user-service
COPY ./services/user-service/package*.json ./
RUN npm install

COPY ./services/user-service/nodemon.json ./

EXPOSE 4000

CMD ["npm", "run", "dev"]
